# Generated by Django 2.1 on 2019-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('cv', models.FileField(upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='myphoto/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='protfolio_img/')),
                ('name', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
