# Generated by Django 2.1 on 2019-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190518_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text2',
        ),
    ]
