# Generated by Django 2.1 on 2019-05-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_about_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
    ]
